### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by hhabakuk** [karmelp/todo#5]
**Üldised mured:**

showTask funktsioon genereerib päris mitmeid konteinereid, mida pole tarvis  ehk sul on tihtipeale kast, mille sees on kast, mille sees on kaks kasti, kui piisaks vaid kastist, mille sees on kaks kasti. 

showTask teeb nii palju asju, et raske on järge pidada - eraldame komponentide genereerimise eraldi funktsioonidesse.

**Järjestatud tükeldatud plaan murede lahendamiseks:**

1. eemalda taskListItemEl - see on lisakonteiner mida pole vaja
2. kasuta awesomefontsi ka done ikooni jaoks
3. eemalda done ikooni span element - topeltkonteinerit pole vaja
4. eemalda delete ikooni ümbert li element ja span element
5. koosta eraldi funktsioon, mis tagastab status button elemendi ning kasuta seda funktsiooni showTask funkstiooni sees
6. koosta eraldi funktsioon, mis tagastab delete button elemendi ning kasuta seda funktsiooni showTask funkstiooni sees
7. koosta eraldi funktsioon, mis tagastab task title elemendi ning kasuta seda funktsiooni showTask funkstiooni sees
8. koosta eraldi funktsioon, mis paneb tehtuks märgitud taskile teised stiilid ning kasuta seda funktsiooni showTask funkstiooni sees
9. kui samale elemendile pannakse mitu last, kasuta el.append(laps1, laps2) süntaksit.
10. eemalda delete iconi ümbert button element - i peal saab ka klikida
11. eemalda done iconi ümbert button element - i peal saab ka klikida
12. nimeta taskDelete algusega asjad ümber deleteTask algusega
13. korrasta showTask funkstsioon : kõige üleval read, mis teevad konteineri, siis read, mis teevad komponendid ja siis read, mis panevad komponendid konteinerisse
14.  igal pool kus teed `el.setAttribute("class", "nimetus")` tee `el.className="nimetus"`
15. vali üks, kas `buttonIcon` või `button_icon` klass? 
Btw HTML klasse kirjutatakse kebab-casega, hetkel okei kui tahad camelCasega kirjutada kuna Reactis tehakse nii, aga snake_case pole õigustatud siinpuhul. https://juniortoexpert.com/en/naming-convention/
16. eralda funktsioon `onAddNewTaskBtnClick`
17. korrasta script.js: tõsta funkstioonid kõrgemale ja funktsioonikäivitamised faili lõppu järjest
18. korrasta css fail - eemalda klassid, mida ei kasuta

**Comment by hhabakuk** [comment]
SPOILER ON ALL!!! 
KASUTA SIIS KUI OLED KINNI JOOKSNUD, ET SPIKERDADA!

-----------
-----------
-----------
-----------
-----------
-----------
-----------














```
const tasks = [
  { title: "Exercise 1", isDone: true },
  { title: "Exercise 2", isDone: false },
];

function getStatusBtnElement(task) {
  const statusIconEl = document.createElement("i");
  statusIconEl.className = "icon fa-solid fa-circle-check button taskStatusBtn";
  statusIconEl.setAttribute("task-title", task.title);
  statusIconEl.onclick = () => toggleTaskStatus(statusIconEl);

  return statusIconEl;
}

function getDeleteBtnElement(task) {
  const deleteTaskIconEl = document.createElement("i");
  deleteTaskIconEl.className = "icon fa-solid fa-trash button deleteTaskBtn";
  deleteTaskIconEl.onclick = () => deleteTask(task);

  return deleteTaskIconEl;
}

function getTaskTitleElement(taskTitle) {
  const taskTitleEl = document.createElement("div");
  taskTitleEl.setAttribute("class", "taskTitle");
  taskTitleEl.setAttribute("task-title", taskTitle);
  taskTitleEl.textContent = taskTitle;

  return taskTitleEl;
}

function markTaskAsDone(statusIcon, taskTitle) {
  statusIcon.style.color = "#42b883";
  taskTitle.style.textDecoration = "line-through";
  taskTitle.style.textDecorationThickness = "2px";
}

function showTask(task) {
  const taskListEl = document.querySelector(".taskList");
  const taskListItemContainerEl = document.createElement("div");
  taskListItemContainerEl.setAttribute("class", "taskListItemContainer");

  const taskStatusEl = getStatusBtnElement(task);
  const taskTitleEl = getTaskTitleElement(task.title);
  const deleteTaskEl = getDeleteBtnElement(task);
  const taskToolsEl = document.createElement("ul");
  taskToolsEl.className = "taskTools";

  if (task.isDone) {
    markTaskAsDone(taskStatusEl, taskTitleEl);
  }

  taskToolsEl.appendChild(deleteTaskEl);
  taskListItemContainerEl.append(taskStatusEl, taskTitleEl, taskToolsEl);
  taskListEl.appendChild(taskListItemContainerEl);
}

function toggleTaskStatus(el) {
  tasks.map((task) => {
    if (task.title === el.getAttribute("task-title")) {
      task.isDone = !task.isDone;
    }
  });

  showNumberOfDoneTasks();
  showAllTasks();
}

function showAllTasks() {
  const taskListEl = document.querySelector(".taskList");
  taskListEl.innerHTML = "";
  tasks.forEach((task) => {
    showTask(task);
  });
}

function onAddNewTaskBtnClick() {
  if (document.querySelector(".newTaskField input").value.length == 0) {
    alert("Write a task first!");
  } else {
    const taskTitle = document.getElementById("newTaskInput").value;
    tasks.push({ title: taskTitle, isDone: false });
    showNumberofAllTasks();
    showAllTasks();
  }
  document.getElementById("newTaskInput").value = "";
}

function showNumberofAllTasks() {
  const allTasksCount = document.querySelector(".allTasksCount");
  allTasksCount.textContent = tasks.length;
}

function showNumberOfDoneTasks() {
  const doneTasksCount = document.querySelector(".doneTasksCount");
  let doneTasksCounter = 0;

  for (let i = 0; i < tasks.length; i++) {
    if (tasks[i].isDone === true) doneTasksCounter++;
  }

  doneTasksCount.textContent = doneTasksCounter;
}

function deleteTask(task) {
  const deleteIndex = tasks.indexOf(task);
  tasks.splice(deleteIndex, 1);

  showAllTasks();
  showNumberOfDoneTasks();
  showAllTasks();
}

document.querySelector(".addNewTaskButton").onclick = onAddNewTaskBtnClick;

showNumberofAllTasks();
showNumberOfDoneTasks();
showAllTasks();
```

**Comment by karmelp** [comment]
> 1. eemalda taskListItemEl - see on lisakonteiner mida pole vaja

On ikka vaja - stiili jaoks. Seda ei saa ära võtta. :(

**Comment by karmelp** [comment]
> 2\. kasuta awesomefontsi ka done ikooni jaoks

Tehtuud!

**Comment by karmelp** [comment]
> 3\. eemalda done ikooni span element - topeltkonteinerit pole vaja

Samamoodi. Stiil on korda sätitud nii. Ei saaaaa!

**Comment by karmelp** [comment]
> 4\. eemalda delete ikooni ümbert li element ja span element

NNNO! :D

**Comment by hhabakuk** [comment]
> > 1. eemalda taskListItemEl - see on lisakonteiner mida pole vaja
> 
> On ikka vaja - stiili jaoks. Seda ei saa ära võtta. :(


> > 3. eemalda done ikooni span element - topeltkonteinerit pole vaja
> 
> Samamoodi. Stiil on korda sätitud nii. Ei saaaaa!

> > 4. eemalda delete ikooni ümbert li element ja span element
> 
> NNNO! :D


mina saiiiiin klasse saab teistele komponentidele panna kaaa

**Comment by karmelp** [comment]
> > > 1. eemalda taskListItemEl - see on lisakonteiner mida pole vaja
> > 
> > 
> > On ikka vaja - stiili jaoks. Seda ei saa ära võtta. :(
> 
> > > 3. eemalda done ikooni span element - topeltkonteinerit pole vaja
> > 
> > 
> > Samamoodi. Stiil on korda sätitud nii. Ei saaaaa!
> 
> > > 4. eemalda delete ikooni ümbert li element ja span element
> > 
> > 
> > NNNO! :D
> 
> mina saiiiiin klasse saab teistele komponentidele panna kaaa

no ei saa. kohe essa ära vöttes ja seda klassi mujale pannes  ja seda stiili mujale pannes, kohe ei ole enam välimus korras. ma keeldun neid eemaldamast :D

**Comment by hhabakuk** [comment]
> 



> > > > 1. eemalda taskListItemEl - see on lisakonteiner mida pole vaja
> > > 
> > > 
> > > On ikka vaja - stiili jaoks. Seda ei saa ära võtta. :(
> > 
> > 
> > > > 3. eemalda done ikooni span element - topeltkonteinerit pole vaja
> > > 
> > > 
> > > Samamoodi. Stiil on korda sätitud nii. Ei saaaaa!
> > 
> > 
> > > > 4. eemalda delete ikooni ümbert li element ja span element
> > > 
> > > 
> > > NNNO! :D
> > 
> > 
> > mina saiiiiin klasse saab teistele komponentidele panna kaaa
> 
> no ei saa. kohe essa ära vöttes ja seda klassi mujale pannes ja seda stiili mujale pannes, kohe ei ole enam välimus korras. ma keeldun neid eemaldamast :D


Siis alusta CSSiga uuesti ja mudi stiile kuniks on korras. :D
või tee katkine commit ja näita mulle, kus sa arvad, et ainuke võimalus stiilid korda teha on teha ühelapselisi kaste.
